name: 🚀 A∞ZAI Threat PoC Deployment & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 📦 Install Dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements needed"

      - name: ⚙️ Run Threat Agent
        run: |
          python PoC/threat_agent.py || echo "Threat Agent Executed"

      - name: ✅ Run Protection Scan
        run: |
          python protection/protector.py || echo "Protection Scan Done"

      - name: 🔍 Run Simple Collector
        run: |
          python PoC/simple_collector.py || echo "Simple Collector Done"